# Generated by Django 5.2.5 on 2025-09-05 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7198e3a2-33a0-45ee-93a4-39c06506a6e0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
