# Generated by Django 5.2.5 on 2025-09-05 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ffe2005-d9e1-4714-9e0e-64315b41e9a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
